name: cai_tool_app
description: 彩数工具 - 纯净的竞彩数据与模型分析工具
publish_to: none
version: 1.0.0+3

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.5.0
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
